# Generated by Django 4.2 on 2026-04-10 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Дугаар')),
                ('title', models.CharField(max_length=200, verbose_name='Гарчиг')),
                ('description', models.TextField(verbose_name='Тайлбар')),
                ('status', models.CharField(choices=[('draft', 'Ноорог'), ('submitted', 'Илгээгдсэн'), ('forwarded', 'Дамжуулагдсан'), ('approved', 'Зөвшөөрөгдсөн'), ('rejected', 'Татгалзагдсан'), ('returned', 'Буцаагдсан'), ('cancelled', 'Цуцлагдсан')], default='draft', max_length=20, verbose_name='Төлөв')),
                ('priority', models.CharField(choices=[('urgent', 'Яаралтай'), ('high', 'Өндөр'), ('normal', 'Энгийн'), ('low', 'Бага')], default='normal', max_length=10, verbose_name='Яаралтай зэрэг')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дуусах огноо')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Нэмэлт мэдээлэл')),
                ('return_count', models.IntegerField(default=0, verbose_name='Буцаалтын тоо')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Ноорог эсэх')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Цуцлагдсан эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчлэгдсэн')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Илгээсэн')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Хаагдсан')),
            ],
            options={
                'verbose_name': 'Өргөдөл',
                'verbose_name_plural': 'Өргөдлүүд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('description', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('required_fields', models.JSONField(blank=True, default=list, verbose_name='Шаардлагатай талбарууд')),
                ('requires_attachment', models.BooleanField(default=False, verbose_name='Хавсралт заавал')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Өргөдлийн төрөл',
                'verbose_name_plural': 'Өргөдлийн төрлүүд',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DecisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Илгээсэн'), ('forward', 'Дамжуулсан'), ('return', 'Буцаасан'), ('approve', 'Зөвшөөрсөн'), ('reject', 'Татгалзсан'), ('cancel', 'Цуцалсан'), ('resubmit', 'Дахин илгээсэн')], max_length=20, verbose_name='Үйлдэл')),
                ('comment', models.TextField(blank=True, verbose_name='Тайлбар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Огноо')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Үйлдэл хийсэн хүн')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='applications.application', verbose_name='Өргөдөл')),
            ],
            options={
                'verbose_name': 'Шийдвэрийн түүх',
                'verbose_name_plural': 'Шийдвэрийн түүхүүд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=255, verbose_name='Файлын нэр')),
                ('file_size', models.IntegerField(default=0, verbose_name='Файлын хэмжээ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Оруулсан огноо')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='applications.application', verbose_name='Өргөдөл')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оруулсан хүн')),
            ],
            options={
                'verbose_name': 'Хавсралт',
                'verbose_name_plural': 'Хавсралтууд',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='app_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applications.applicationtype', verbose_name='Төрөл'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Өргөдлийн эзэн'),
        ),
    ]
