# Generated by Django 4.2 on 2026-04-10 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_apps', to=settings.AUTH_USER_MODEL, verbose_name='Хариуцах захирал'),
        ),
        migrations.AlterField(
            model_name='application',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Маш яаралтай'), ('high', 'Яаралтай'), ('normal', 'Энгийн')], default='normal', max_length=10, verbose_name='Ач холбогдол'),
        ),
    ]
